version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: b2bnetloom-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: b2bnetloom
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
